# Python

## Algunas cuestiones importantes:

- Python es un lenguaje interpretado : *An interpreted language is a language in which the implementations execute instructions directly without earlier compiling a program into machine language*

- Utiliza tipado fuerte y dinamico : *The term dynamic typing means that a compiler or an interpreter assigns a type to all the variables at run-time*

- Uno de sus paradigmas (algo en lo que esta basado el lenguaje) es la orientacion a objetos.

- La filosofia del lenguaje esta descripta en el PEP 020

- El estilo de codigo que se espera en Python esta sumarizado en el PEP 008

# Practica de conceptos de Numpy

- *np.arange(start,stop,step).reshape((n,m))* : Para poder generar matrices del tamanio que deseemos
- puedes especificar el tipo de los elementos utilizando *dtype*

In [5]:
import numpy as np
a = np.arange(1,10,1 , dtype=float)
print(a)
print(a.shape)
print(a.reshape((3,3)))


[1. 2. 3. 4. 5. 6. 7. 8. 9.]
(9,)
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


- Es posible crear matrizes solo de ceros y unos o bien de elementos true o false especificando *dtype=bool*

In [7]:
print(np.zeros((3,3),dtype=bool))
print(np.ones((2,3),dtype=bool))

[[False False False]
 [False False False]
 [False False False]]
[[ True  True  True]
 [ True  True  True]]


- *np.isfinite()* : Test element-wise for finiteness (not infinity and not Not a Number)
- *np.isinf()* : Test element-wise for positive or negative infinity

In [9]:
print(np.arange(1,15,1,dtype=float))
print(np.isfinite(np.arange(1,15,1,dtype=float)))
print(np.isinf(np.arange(1,15,1,dtype=float)))

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14.]
[ True  True  True  True  True  True  True  True  True  True  True  True
  True  True]
[False False False False False False False False False False False False
 False False]


- *np.linspace(start,stop,num)* : Return evenly spaced numbers over a specified interval</br>
Returns num evenly spaced samples, calculated over the interval [start, stop]


In [10]:
print(np.linspace(1,10,20))
print(np.linspace(1,10,20).shape)

[ 1.          1.47368421  1.94736842  2.42105263  2.89473684  3.36842105
  3.84210526  4.31578947  4.78947368  5.26315789  5.73684211  6.21052632
  6.68421053  7.15789474  7.63157895  8.10526316  8.57894737  9.05263158
  9.52631579 10.        ]
(20,)


- *id()* : Returns a unique integer number for every unique value it is used with

In [11]:
print(id(5))
print(id(4))
print(id(5)==id(5))

140728095990696
140728095990664
True


- Simbolos comprimidos: a += 2 ----> a = a + 2

In [14]:
a = 5
a += 2
print(a)


7
