In [80]:
import scipy
import numpy as np
from scipy import sparse

In [38]:
vector1 = [np.array([1,1,1]),np.array([2,2,2]),np.array([3,3,3])]
vector2 = [np.array([0,0,0])]
vector1

[array([1, 1, 1]), array([2, 2, 2]), array([3, 3, 3])]

In [22]:
d = scipy.spatial.distance.cdist(vector2,vector1, metric='euclidean')
print(d)

[[1.73205081 3.46410162 5.19615242]]


In [92]:
a = [1,1,1,0]
b = [2,2,2,0]
c = [3,3,3,0]
d = np.array([a,b,c])
d = np.transpose(d)
origin = np.array([[0,0,0]])
origin1 = np.array([[1,1,1]])
d

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3],
       [0, 0, 0]])

In [93]:
e = scipy.spatial.distance.cdist(origin,d, metric='euclidean')
f = scipy.spatial.distance.cdist(origin1,d, metric='euclidean')
arr = []
arr.append(e[0])
arr.append(f[0])
arr


[array([3.74165739, 3.74165739, 3.74165739, 0.        ]),
 array([2.23606798, 2.23606798, 2.23606798, 1.73205081])]

In [96]:
sA = sparse.csr_matrix(arr)
print(sA.toarray())

[[3.74165739 3.74165739 3.74165739 0.        ]
 [2.23606798 2.23606798 2.23606798 1.73205081]]


In [48]:
a = np.array([[0, 0, 0],
              [0, 0, 1],
              [0, 1, 0],
              [0, 1, 1],
              [1, 0, 0],
              [1, 0, 1],
              [1, 1, 0],
              [1, 1, 1]])
b = np.array([[ 0.1,  0.2,  0.4]])
#scipy.spatial.distance.cdist(b, a, 'cityblock')
b

array([[0.1, 0.2, 0.4]])

In [70]:
a = np.array([101, 99, 87])
b = np.array([897, 97, 111])
alpha = np.greater(a, b).astype(float)
print(alpha)

[0. 1. 0.]


In [78]:
array = np.array([])
a = np.append(array,5.)
a

array([5.])